### ISSUE TITLE
Fill simulators with pseudocode

### ISSUE THREAD

**Issue by paxuy** [juliushaag/Quafel-PSE-2024#32]

**Comment by nils-prommersberger** [comment]
Das ist noch nicht genug. Es fehlen:
- wir hatten in der gestern mit Melvin über dieses slum:// gesprochen, das muss überprüft werden und dann evt. eine andere Funktion?
- das generell Aufteilen in Funktionen ist sehr erwünscht. 
- also eventuell den setup in eine eigene Funktion, die ein bool zurückgibt, wenn es erfolgreich war, 
- den in der eigentlichen Funktion checken und weitermachen (kleine statements dürfen schon in richtigen code geschrieben werden)
