### ISSUE TITLE
Write the output of a simulation in the database

### ISSUE THREAD

**Issue by nils-prommersberger** [juliushaag/Quafel-PSE-2024#67]
To get the output check the state of a request inside the submitter and get the output if it is READY. If it returns ERROR, call the get_output function to clean the process up and start it again. 
The get_output function returns the csv data as a string.

**Comment by nils-prommersberger** [comment]
Der Output einer Simulation kann im submitter als csv abgerufen werden. Dies muss noch in die Datenstruktur Djangos übersetzt und in die Datenbank geschrieben werden. Am besten in einer View, immer wenn eine Seite geöffnet wird (/view, /simulations)

**Comment by juliushaag** [comment]
Added a middleware, which can be used to check the current status, it is called every time ANY webpage is requested from django

**Comment by nils-prommersberger** [comment]
Die middleware wird momentan nicht genutzt. Dem thread der Submittierung wird eine Funktion übergeben, welche die Daten in die Datenbank schreibt.
