### ISSUE TITLE
The last admin can remove himself

### ISSUE THREAD

**Issue by nils-prommersberger** [juliushaag/Quafel-PSE-2024#82]
This should not be bossible

**Comment by Chakr0** [comment]
Last admin cannot be removed atm.

**Comment by Chakr0** [comment]
Is the identification necessary?

**Comment by nils-prommersberger** [comment]
> Last admin cannot be removed atm.

Wenn man unter accounts alle e-Mails löscht, sich abmeldet und wieder versucht sich anzumelden, hat man keinen Zugriff mehr. -> Der letzte Admin kann gelöscht werden. 



> Is the identification necessary?
Wenn du die Identifikation in der DB meinst: Ja, die ist notwendig, da durch die e-Mail, die in der identification steht geprüft wird, ob der angemeldete kit-Account Zugriff hat oder nicht. 
Wenn du etwas anderes meinst, musst du mehr ins Detail gehen.
